services:
  - type: web
    name: resume-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CORS_ORIGINS
        value: https://resume-updater-flax.vercel.app,http://localhost:3000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: debug
    plan: starter