services:
  - type: web
    name: resume-api
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y texlive && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false